#!/bin/bash

############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script runs aircrack-ng with the bigger pcapdump file
#    int the folder ~/kismet and a wordlist
#
#  USAGE
#    airkiss WORDLIST-FILE
##


echo 'Running:'
echo  'aircrack-ng ~/kismet/'$(ls ~/kismet/ --sort=size | head -n 1)' -w '$1
aircrack-ng ~/kismet/$(ls ~/kismet/ --sort=size | head -n 1) -w $1
