#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script prints a list of docker commands.
#
#  USAGE
#    gdocker
##


echo -e "\e[40m\e[91m\nCheck for running containers:\n# docker ps\n"

echo -e "\e[94mList all containers running on the host for deletion:\n# docker ps -a\n"

echo -e "\e[97mStop a running container:\n# docker stop <CONTAINER ID>\n"

echo -e "\e[33mKilling still running containers:\n# docker kill <CONTAINER ID>\n"

echo -e "\e[95mDelete all containers listed by ID:\n# docker rm <CONTAINER ID>\n"

echo -e "\e[91mList all Docker images:\n# docker images\n"

echo -e "\e[94mDelete all images by ID:\n# docker rmi <IMAGE ID>\n"

echo -e "\e[97mDelete all images, containers, volumes, and networks that are not associated with a container (dangling):\n# docker system prune\n"

echo -e "\e[33mTo additionally remove any stopped containers and all unused images (not just dangling ones), add the -a flag to the command:\n# docker system prune -a\n"

echo -e "\e[39m\e[49m"

