#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script update time from a ntp server.
#
#  USAGE
#    gclock
##

sudo ntpdate -u a.st1.ntp.br

