#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script finds an IP of a machine from 
#    the network address and the MAC-ADDRESS
#
#  USAGE
#    getip NETWORK-ADDRESS MAC-ADDRESS
##


sudo nmap -sn $1 > pinglan
cat pinglan | grep -B 2 $2
