#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script finds names of hosts from the lan network address
#
#  USAGE
#    getnames NETWORK-ADDRESS
##


sudo nmap -sn $1 > pinglan
ips=$(cat pinglan | grep "Nmap scan report for" | awk '{print $5}')

# Use this if you need to cut '(' and ')'  
# ips=$(cat pinglan | grep "Nmap scan report for" | grep -Po '(?<=\().*(?=\))' | awk '{print $5}')

red='\033[0;31m'
nc='\033[0m'
for i in ${ips[@]}
do
	echo -e "${red}host in IP${nc} "$i
	sudo host $i
done

