#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script clones a github or bitbucket repository
#    from the git global user
#
#  USAGE
#	BITBUCKET CLONE
#    ggitclone -b REPOSITORY-NAME
#   GITHUB CLONE
#	 ggitclone -g REPOSITORY-NAME
##

if [ $1 == "-b" ]
then
	git clone git@bitbucket.com:"$(git config user.name)"/"$2".git
elif [ $1 == "-g" ]
then
	git clone git@github.com:"$(git config user.name)"/"$2".git
else
	echo "There is no option: "$1" .Nothing Done!"
fi

