#!/usr/bin/env bash
#
# gsh - Derives an HMAC from a password and salt using a specified OpenSSL digest
#
# Copyright (c) 2015-2026, Augusto Damasceno.
# All rights reserved.
# SPDX-License-Identifier: GPL-3.0
#
# See https://github.com/augustodamasceno/gsh
#
# Usage: ghmac DIGEST PASSWORD SALT
#		rmd160
#		sha
#		sha1
#		sha224
#		sha256
#		sha384
#		sha512
##

echo -n $2 | openssl $1 -hmac $3

