#!/bin/bash


##
#  This script is part of the GSH software.
#
#  This script is a git cheat sheet.
#
#  References:
#		https://www.atlassian.com/git/tutorials/atlassian-git-cheatsheet
#		http://guides.beanstalkapp.com/version-control/common-git-commands.html
##


echo "
GSH Git Cheat Sheet

>> List configuration.
git config --list

>> Define name, email and signing key locally.
git config user.name <name>
git config user.email <email>
git config user.signingkey <key>

>> Define name, email and signing key globally.
git config --global user.name <name>
git config --global user.email <email>
git config --global user.signingkey <key>

>> Create empty git repo.
git init

>> Clone a repo.
git clone https://<IP>/<USER>/<REPO>
git clone git@<IP>:<USER>/<REPO>.git

>> Add file, folder or all files not defined in .gitignore to the index.
git add <file>
git add <folder>
git add --all

>> Remove file from remote
git rm --cached <file>
git commit -m \"<message>\"
git push -u origin <branch>

>> Commit.
git commit -m \"<message>\"

>> List which files are staged, unstaged, and untracked.
git status

>> Pulls the changes from the remote repository.
git pull <remote> <branch>
git pull origin <branch>

>> Sends local commits to the remote repository. 
git push <remote> <branch>
git push origin <branch>

>> Delete local branch
git branch -d <branch>

>> Delete remote branch
git push <remote> :<branch>
git push origin :<branch>

>> Display the entire commit history 
git log

>> Display the full diff of each commit.
git log -p

>> Display n last commits
git log -<n>

>> Show unstaged changes between your index and working directory.
git diff
" | less
