#!/usr/bin/env bash
#
# gsh - Kills all processes whose name matches the given string
#
# Copyright (c) 2015-2026, Augusto Damasceno.
# All rights reserved.
# SPDX-License-Identifier: GPL-3.0
#
# See https://github.com/augustodamasceno/gsh
#
# Usage: gkill PROCESS-NAME


name=$1
ps aux | awk '{ print $2, $11}' | grep $name | awk '{print $1}' | xargs kill -9

