#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script return the IPv4 or IPv6 from a name.
#
#  USAGE
#	IPv4
#     glookup -4 NAME
#	IPv6
#     glookup -6 NAE
##


USAGE=" 
USAGE:\n\n
-4 <NAME> : IPv4\n
-6 <NAME> : IPv6.\n\n
EXAMPLE:\n\n
glookup -4 github.com\n"

if [ $# -eq 2 ]
then
	if [ $1 == "-4" ]
	then
		ping -4 -c 1 $2 | head -n 1 | awk -F'[)(]' -v n=1 '{ print $2 }'
	elif [ $1 == "-6" ]
	then
		ping -6 -c 1 $2 | head -n 1 | awk -F'[)(]' -v n=1 '{ print $2 }'
	else
	echo -e $USAGE	
	fi
else
	echo -e $USAGE
fi
