#!/bin/bash


##
#  This script is part of the GSH software.
#
#  This script adds a prefix to all files in the current folder.
#
#  USAGE
#    gmvpre PREFIX
##


pre=$1
if [ ${#1} -gt 0 ]
then
	userMsg1='Rename all files in this folder adding the prefix \042'
	echo -n $userMsg1$pre'\042 (y/N) '
	read ok
	
	if [ "$ok" = "Y" ]; then ok="y";fi
	if [ "$ok" = "y" ]
	then
		for i in *
		do
			newname=$pre$i
			echo "renaming $i to $newname"
			mv $i $newname
		done
		mv $0$pre $0
	fi
fi

