#!/bin/bash


##
#  This script is part of the GSH software.
#
#  This script creates a new python virtual environment 
#    in the folder ~/.venv
#
#  USAGE
#    gnenv VENV-NAME
##


if ! [ -d ~/.venv/ ]
then
	mkdir ~/.venv/
fi
virtualenv -p `which python3` "~/.venv/$1"

