#!/usr/bin/env bash
#
# gsh - Merges PDFs or converts images to a single PDF in the current directory
#
# Copyright (c) 2015-2026, Augusto Damasceno.
# All rights reserved.
# SPDX-License-Identifier: GPL-3.0
#
# See https://github.com/augustodamasceno/gsh
#
# Usage: gpdf -m OUT | -cp OUT | -cj OUT

if [ $1 == "-m" ]
then
	pdftk *.pdf cat output $2
elif [ $1 == "-cp" ]
then
	convert *.png $2
elif [ $1 == "-cj" ]
then
	convert *.jpg $2
else
	echo "There is no option: "$1" .Nothing Done!"
fi

