#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script runs ps aux with human readable sizes.
#
#  USAGE
#    gps
##


ps aux | numfmt --header --to=iec --field 5,6 --padding 6

