#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script shows all users with processes running
#
#  USAGE
#    gpsu
##


ps aux | awk '{print $1}' | uniq -u

