#!/usr/bin/env bash
#
# gsh - Generates a QR code PNG from the contents of a text file using qrencode
#
# Copyright (c) 2015-2026, Augusto Damasceno.
# All rights reserved.
# SPDX-License-Identifier: GPL-3.0
#
# See https://github.com/augustodamasceno/gsh
#
# Usage: gqrcode TEXT-FILE IMAGE-OUTPUT


cat $1 | qrencode -o $2 -l M -s 5

