#!/usr/bin/env bash
#
# gsh - Generates a random base64 string of a given byte length
#
# Copyright (c) 2015-2026, Augusto Damasceno.
# All rights reserved.
# SPDX-License-Identifier: GPL-3.0
#
# See https://github.com/augustodamasceno/gsh
#
# Usage: grand NUM-CHARS [-o|-r]

if [ $# -eq 0 ]; then
	cat /dev/urandom | base64 | head -c 16
elif [ $# -eq 1 ]; then
	cat /dev/urandom | base64 | head -c $1
elif [ $# -eq 2 ] && [ "$2" == "-o" ]; then 
	openssl rand -base64 $1
elif [ $# -eq 2 ] && [ "$2" == "-r" ]; then 
	cat /dev/random | base64 | head -c $1
else
	echo "Invalid Option. USAGE: grand <NUMBER-OF-CHARACTERS [-o|-r]>"
fi
