#!/usr/bin/env bash
#
# gsh - Rsyncs source to destination with checksum comparison and a progress bar
#
# Copyright (c) 2015-2026, Augusto Damasceno.
# All rights reserved.
# SPDX-License-Identifier: GPL-3.0
#
# See https://github.com/augustodamasceno/gsh
#
# Usage: grsync SOURCE DESTINATION

# Print a message to the user about the number of files and the rsync options.
nfiles=$(find $1 -type f | wc -l)
echo "Syncing "$nfiles" files from "$1" to "$2"." 
echo "Skip based on checksum!"

# Rsync with pv to show the progess.
rsync -cav $1 $2 | pv -lpe -s $nfiles > /dev/null

