#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

# Print a message to the user about the number of files and the rsync options.
nfiles=$(find $1 -type f | wc -l)
echo "Syncing "$nfiles" files from "$1" to "$2"." 
echo "Skip based on checksum!"

# Rsync with pv to show the progess.
rsync -cav $1 $2 | pv -lpe -s $nfiles > /dev/null

