#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script Display Linux processes by resources (top 3).
#
#  USAGE
#    gtop
##


printf '\033[0;31m----------TOP CPU USE--------\033[0m\n'
ps aux | head -1
ps aux | sort -rn -k 3,6 | head -3
printf '\033[0;31m----------TOP MEMORY USE--------\033[0m\n'
ps aux | head -1
ps aux | sort -rn -k 4,6 | head -3

