#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script runs memcheck from valgrind to search for memory leaks.
#
#  USAGE
#    gvalgrind ./THE-PROGRAM
##



valgrind --leak-check=full --track-origins=yes $1

