#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script generates a public IP log.
#
#  Run this script inside a synchronized 
#    folder to access the public ip info anywhere.
#    See https://github.com/kennethreitz/httpbin
#
#  USAGE
#   pubiplog 
##


if (test -e ip-public.txt)
then
		mv ip-public.txt ip-public.backup$(date +"%d%h%y_%H-%M-%S").txt
		echo 'Backing up the previous log.'
fi

while true
do
	date >> ip-public.txt
	curl http://httpbin.org/ip >> ip-public.txt 	
	sleep 60
done

