#!/bin/bash
############################################
# This script is part of the GSH software.
# # Copyright (c) 2015-2023, Augusto Damasceno.
# All rights reserved.  
# SPDX-License-Identifier: GPL-3.0
############################################

##
#  This script is part of the GSH software.
#
#  This script downloads all images in a website.
#
#  USAGE
#    webimages WEBSITE
##


wget -r -A jpeg,jpg,bmp,gif,png $1
